# reference http://abhiesa.github.io/2014/10/20/travis/
language: node_js
node_js:
  - "0.11"
branches:
  only:
  - master
before_install:
- npm install -g hexo
install:
- npm i
before_script:
- git config --global user.name 'wayou'
- git config --global user.email 'liuwayong@gmail.com'
script:
- hexo o
after_success:
- mkdir .deploy
- cd .deploy
- git clone --depth 1 --branch master --single-branch $DEPLOY_REPO . || (git init && git remote add -t master origin $DEPLOY_REPO)
- rm -rf ./*
- cp -r ../public/* .
- git add -A .
- git commit -m 'Auto Update from TRAVIS-CI'
- git branch -m master
- git push -q $DEPLOY_REPO HEAD:master