# reference http://abhiesa.github.io/2014/10/20/travis/
language: node_js
node_js:
  - "0.11"
branches:
  only:
  - master
before_install:
- npm install -g hexo@2.8.3
install:
- npm i
before_script:
- git config --global user.name 'wayou'
- git config --global user.email 'liuwayong@gmail.com'
script:
- hexo o -d