#slogan: ""

menu:
  - title: 首页
    url: 
    intro: "首页"
    icon: "fa fa-home"
  - title: 存档
    url: archives
    intro: "全部文章"
    icon: "fa fa-list"
  - title: 分类 
    url: categories
    intro: "所有分类"
    icon: "fa fa-folder"
  - title: 关于
    url: about
    intro: "简介"
    icon: "fa fa-info-circle"
  - title: RSS
    url: atom.xml
    intro: "订阅"
    icon: "fa fa-rss"
  - title: GitHub
    url: https://github.com/wayou
    intro: "GitHub"
    icon: "fa fa-github-alt"

links:
  - title: "source"
    url: http://www.github.com/wayou
    intro: "My Github account."
    icon: "fa fa-github"

widgets:
# - search
- category
# - tagcloud
- recent_posts  
- links

rss: 
fancybox: false
favicon: favicon.png
google_analytics: 